### ISSUE TITLE
Naming convention (methods and vars)

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#1]
@edwin-roque-0723 por favor revisar la nomenclatura de los procedimientos con excepción de las etapas de precarga de archivos y archivos de inicialización. Sugiero que para los métodos sea algo así como procesarArchivos() o getBackground(), etc.

~Diego

**Comment by edwin-roque-0723** [comment]
He estado eliminando esa nomenclatura con los guiones, pero hay algunos que se me han pasado.  Ahora los cambio
