### ISSUE TITLE
Change AddError for addErrorIndividual

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#16]
Cambiemos el archivo layer0-prerequistes.R y borramos la función addErrorIndividual.

**Comment by edwin-roque-0723** [comment]
Ya lo cambié y funciona bien; más bien estaba pensando en crear una función que simplifique la tabla que  en cada error como lo hablamos hace unos días, reduciría líneas de código
