### ISSUE TITLE
Remove (NA)

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#17]
311 Se identificaron 01 crédito(s)/garantía(s) vacias en la BD01 correspondiente al periodo de setiembre del 2020.(NA)

Cuando sale el error 311 sale (NA) al final, entiendo que si hay 10 vacíos saldra (NA,NA,NA ...), please borrar todo el parentesis al final dl error.

**Comment by edwin-roque-0723** [comment]
lo acabo de cambiar
