### ISSUE TITLE
cut off output string 

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#18]
En lugar de reportar este error:

Se identificaron 658 garantía(s) que no figuran en la base de datos de garantía entrega BD03A correspondiente al periodo de noviembre del 2019.(185, 1196, 1224, 1444, 73, 1183, 88, 1125, 1119, 713, 1388, 1288, 786, 1573, 1305, 1519, 1378, 335, 1541, 1510, 473, 1574, 4095, 1031, 210, 1410, 4055, 1233, 158, 1453, 942, 310, 789, 1435, 1071, 1542, 4032, 72, 392, 1005, 1160, 1149, 1166, 1028, 393, 346, 4052, 689, 1365, 1253, 1197, 93, 174, 504, 1412, 1423, 87, 1492, 1061, 4061, 701, 1190, 767, 85, 1391, 742, 77, 4090, 674, 69, 149, 738, 813, 3999, 39, 1533, 649, 1086, 96, 783, 331, 4071, 347, 1576, 496, 52, 1007, 256, 1532, 756, 985, 489, 65, 1072, 148, 157, 1462, 1151, 666, 1540, 1498, 1204, 753, 1581, 317, 777, 1464, 1222, 287, 425, 123, 1547, 1044, 1042, 122, 216, 749, 90, 1340, 161, 1038, 986, 354, 105, 4075, 1201, 1358, 4094, 4077, 521, 1140, 781, 345, 1591, 602, 1554, 1159, 4093, 688, 746, 1333, 1531, 956, 83, 371, 315, 698, 358, 155, 1447, 4074, 282, 841, 1495, 1501, 1399, 412, 1232, 1449, 535, 120, 1337, 677, 719, 1536, 196, 635, 562, 1027, 716, 1375, 718, 1157, 1451, 1454, 1111, 748, 1181, 1336, 434, 1343, 994, 4031, 592, 342, 456, 1414, 1030, 768, 481, 152, 501, 805, 705, 1082, 902, 574, 613, 1499, 145, 1430, 1211, 516, 1278, 1426, 761, 1099, 426, 661, 737, 1522, 268, 257, 19, 918, 1592, 4022, 1509, 68, 1437, 577, 1528, 939, 791, 1101, 667, 858, 4025, 803, 343, 36, 784, 1544, 513, 770, 1327, 1329, 143, 1442, 159, 323, 423, 385, 1559, 126, 390, 411, 372, 735, 1405, 312, 4103, 424, 1436, 1182, 329, 808, 1179, 394, 1185, 536, 758, 1286, 1598, 483, 762, 1051, 197, 293, 427, 804, 1523, 679, 1546, 1225, 304, 724, 78, 1008, 1424, 4054, 454, 4081, 603, 1505, 491, 3983, 94, 991, 774, 28, 1110, 1000, 443, 80, 730, 91, 1347, 4086, 822, 1036, 691, 1079, 1097, 951, 344, 4009, 469, 409, 4083, 415, 1108, 437, 519, 990, 706, 1348, 1178, 222, 139, 775, 980, 92, 630, 1557, 814, 790, 226, 484, 807, 508, 1439, 1154, 534, 1508, 983, 1479, 895, 1513, 1364, 452, 458, 166, 431, 401, 1567, 89, 405, 480, 500, 1392, 1026, 29, 1142, 1195, 1558, 856, 57, 4057, 62, 307, 1577, 733, 490, 624, 511, 809, 4079, 1570, 460, 1427, 1198, 744, 3965, 168, 1145, 1416, 1068, 324, 1184, 1057, 1429, 642, 1035, 4034, 1389, 1446, 1118, 1560, 1187, 806, 429, 82, 4100, 327, 272, 1356, 439, 693, 1575, 162, 800, 1406, 492, 4089, 1260, 1551, 739, 4030, 709, 1440, 1476, 1445, 1067, 3934, 510, 1335, 1481, 466, 66, 478, 1538, 1555, 302, 1600, 338, 1023, 1425, 31, 156, 4062, 1413, 468, 453, 1514, 680, 651, 1168, 1257, 1545, 1251, 497, 1496, 4044, 1345, 34, 1194, 1472, 494, 1264, 505, 1216, 1530, 75, 579, 388, 4056, 1100, 743, 518, 1398, 1059, 1595, 875, 1094, 1046, 138, 417, 1152, 1393, 587, 1177, 4066, 1170, 1019, 1165, 507, 4092, 1091, 772, 355, 1585, 1167, 1550, 48, 773, 1293, 1367, 314, 707, 527, 1237, 747, 797, 1088, 334, 1025, 1037, 1572, 10032619, 721, 328, 450, 788, 4006, 383, 113, 4019, 1188, 1199, 596, 1579, 1081, 1543, 1132, 147, 1400, 261, 869, 217, 771, 49, 4088, 612, 1387, 84, 227, 241, 537, 1322, 4048, 1553, 687, 1374, 782, 1599, 655, 664, 1220, 99, 1066, 1458, 517, 45, 1583, 160, 4000, 4087, 1506, 1415, 1394, 1306, 526, 86, 150, 1231, 1526, 74, 1571, 47, 530, 70, 734, 1443, 520, 1382, 140, 846, 653, 929, 1383, 502, 396, 400, 4076, 1078, 3992, 4082, 273, 4102, 685, 1582, 1488, 1433, 4068, 1127, 53, 4098, 1385, 1521, 5, 4035, 1339, 654, 867, 360, 97, 659, 288, 4065, 339, 499, 1294, 671, 269, 1193, 1511, 274, 4011, 1590, 1223, 71, 715, 736, 1112, 281, 348, 639, 911, 1593, 1384, 1534, 362, 1018, 1549, 801, 430, 291, 1487, 1402, 524, 672, 665, 289, 723, 1587, 23, 4059, 1527, 479, 498, 464, 1409, 728, 1173, 1552, 1274, 1277, 1189, 449, 1047, 280, 615, 871, 1076, 163, 475, 692)

Reportar este error:

**Se identificaron 658 garantía(s) que no figuran en la base de datos de garantía entrega BD03A correspondiente al periodo de noviembre del 2019.(185, 1196, 1224, 1444, 73 ... )**

**Comment by edwin-roque-0723** [comment]
Se creó una función (cutStringError) que hará esto cuando el número créditos o garantías sea mayor que 100 por cada código de error, menos en el que se registran las columnas
