### ISSUE TITLE
Output file for header and error-bucket

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#2]
@edwin-roque-0723 por favor generar una función que devuelva dos archivos separados por comas, si el resultado es muy amplio lo podemos cortar e indicar que se cortó por el tamaño de origen. 

~Diego

**Comment by edwin-roque-0723** [comment]
Ya existía una función que hace esto saveResults(), guarda la data (header, error_bucket) en .csv , solo que la modifiqué porque faltaba especificar la ruta completa.
