### ISSUE TITLE
str_replace_all sample.

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#22]
observacion <- c("Esta observación tiene {0} incidente(s), valorizado en S/ {1}, en los periodos {2}.")
      str_replace_all(observacion, c("\\Q{0}"  = "132",
                                     "\\Q{1}"  = "212.32",
                                     "\\Q{2}"  = "enero y febrero de 2020"))

**Comment by edwin-roque-0723** [comment]
ya lo implementé en el ebFormatted y sale bien
