### ISSUE TITLE
test results 30012021

### ISSUE THREAD

**Issue by yakovsingh** [SACOOP-PE/SIA-Analitica-PE#23]
1. Y si tratamos al error 1XX como todos? o sea que se genere uno por cada archivo faltante? eso haría que no tengamos NA's en el bucket. 
![image](https://user-images.githubusercontent.com/48894356/106370997-8a4e5680-632d-11eb-9481-ac6e45cf7f9d.png)
En el bucket que se genere uno por uno, y en el ebformatted que informe todo agrupado. 
Checa si podemos hacerlo, en caso positivo, genera un issue con prioridad media. 

2. Enviarle un correo a Marcia de San Martín para que revise el SFTP y termine de mandar las bases de datos crediticias, entiendo que faltan algunas de noviembre20, si se encuentra fuera de tiempo, dile que mande una carta solicitando prorroga. 

3. Uso este código para convertir todo a utf8

```
Get-ChildItem "C:\dsingh\InstanciaValidadorBDCC\test\datatest" -Filter *.txt -recurse | 
    Foreach-Object {
    Write-Host (Get-Date).ToString() $_.FullName
    Get-Content $_.FullName | Set-Content -Encoding UTF8 ($_.FullName  + 'TMP')
    Copy-Item ($_.FullName  + 'TMP') -Destination $_.FullName  
    Remove-Item -Path ($_.FullName  + 'TMP')  -Force
```
   
Creo que cumple su función no? por que usar el del github y no este que es mas corto ? BTW, se me ocurre hablar con Edgar Pallaroso de GTI y comentarle la idea de tener un código powershell que sincronice las carpetas sftp y que de paso haga esta conversión, pero es ya sería con una workstation. 

4. Guardar los resultados en test/outputs/, actualmente están en test/

5. En esta observación "Se detectaron 45 crédito(s) con cronogramas duplicado(s) en el mes de Enero con un saldo de colocaciones por S/ 2311623.49 durante el periodo enero del 2019." 

Debe constar la coma decimal en el saldo, y el mes en minúscula, o sea: 

"Se detectaron 45 crédito(s) con cronogramas duplicado(s) en el mes de **enero co**n un saldo de colocaciones por** S/ 2,311,623.49** durante el periodo enero del 2019."

6. En esta observación "Se detectaron 1 operación(es) de crédito con cronogramas cancelados duplicados en el periodo 201901 con un saldo de colocaciones por S/ 0 durante el periodo enero del 2019." 

Si el crédito es cancelado (por que entiendo que este crédito se encuentra en la BD02B) entonces no tienen saldo de colocaciones. 

Debe decir así: 
"Se detectaron 1 operación(es) de crédito con cronogramas cancelados duplicados durante el periodo enero del 2019."

7.  En esta observación "Se detectaron 31 código(s) de garantía duplicados en el periodo 201901 con un saldo de colocaciones por S/ 11826082.51 durante el periodo enero del 2019" 

Las garantías tienen coberturas, y los créditos tienen: saldo de colocaciones, saldo por pagar, saldo de capital por amortizar, estos últimos 03 quieren decir lo mismo. 

También si lees la observación, menciona el periodo dos veces. 

En la observación se debe decir: 
"Se detectaron 31 código(s) de garantía duplicados con un monto de cobertura total por S/ 11,826,082.51 durante el periodo enero del 2019" 

El monto de cobertura total es un aproximado, tener cuidado de valorizar la cobertura de la garantía solo 01 vez, o sea si tienen una garantía de 1 millon duplicada 4 veces, la cobertura total es 1 millon, no 4 millones. 

8. Agreguemos un cero adicional por temas de presentación: 
Antes: Se detectaron 1 cronograma(s) faltantes de acuerdo con la cartera reportada en el periodo 202001, los créditos observados tienen un saldo de colocaciones por S/ 708.53 durante el periodo enero del 2020.
Ahora: Se detectaron 01 cronograma(s) faltantes de acuerdo con la cartera reportada en el periodo 202001, los créditos observados tienen un saldo de colocaciones por S/ 708.53 durante el periodo enero del 2020.

en caso tenga dos o más dígitos no agregar ningún cero. 

9. Cambio de forma
Antes: Se detectaron 1 cronograma(s) faltantes de acuerdo con la cartera reportada en el periodo 202001, los créditos observados tienen un saldo de colocaciones por S/ 708.53 durante el periodo enero del 2020.
Ahora: Se detectaron 01 cronograma(s) **faltante(s)** de acuerdo con la cartera reportada en enero del 2020, el saldo de colocaciones de la(s) operación(es) observadas es S/ 708.53.

Además, me parece muy poco el saldo de colocaciones de dicho crédito, corroborémoslo. 

10. Esta jalando mal la cobertura. 

Se detectaron 77   garantía(s) faltantes en el registro correspondiente en el periodo 201901,   por un monto de cobertura de S/ 0 durante el periodo enero del 2019.
--
Se detectaron 459 garantía(s) faltantes   en el registro correspondiente en el periodo 201902, por un monto de   cobertura de S/ 0 durante el periodo febrero del 2019.
Se detectaron 504 garantía(s) faltantes   en el registro correspondiente en el periodo 201903, por un monto de   cobertura de S/ 0 durante el periodo marzo del 2019.
Se detectaron 526 garantía(s) faltantes   en el registro correspondiente en el periodo 201904, por un monto de   cobertura de S/ 0 durante el periodo abril del 2019.
Se detectaron 584 garantía(s) faltantes   en el registro correspondiente en el periodo 201905, por un monto de   cobertura de S/ 0 durante el periodo mayo del 2019.
Se detectaron 619 garantía(s) faltantes   en el registro correspondiente en el periodo 201906, por un monto de   cobertura de S/ 0 durante el periodo junio del 2019.
Se detectaron 2173 garantía(s) faltantes   en el registro correspondiente en el periodo 201907, por un monto de   cobertura de S/ 0 durante el periodo julio del 2019.
Se detectaron 689 garantía(s) faltantes   en el registro correspondiente en el periodo 201908, por un monto de   cobertura de S/ 0 durante el periodo agosto del 2019.
Se detectaron 721 garantía(s) faltantes   en el registro correspondiente en el periodo 201909, por un monto de   cobertura de S/ 0 durante el periodo setiembre del 2019.
Se detectaron 756 garantía(s) faltantes   en el registro correspondiente en el periodo 201910, por un monto de   cobertura de S/ 0 durante el periodo octubre del 2019.
Se detectaron 658 garantía(s) faltantes   en el registro correspondiente en el periodo 201911, por un monto de   cobertura de S/ 0 durante el periodo noviembre del 2019.
Se detectaron 675 garantía(s) faltantes   en el registro correspondiente en el periodo 201912, por un monto de   cobertura de S/ 0 durante el periodo diciembre del 2019.
Se detectaron 13 garantía(s) faltantes en   el registro correspondiente en el periodo 202001, por un monto de cobertura   de S/ 0 durante el periodo enero del 2020.
Se detectaron 13 garantía(s) faltantes en   el registro correspondiente en el periodo 202002, por un monto de cobertura   de S/ 0 durante el periodo febrero del 2020.
Se detectaron 81 garantía(s) faltantes en   el registro correspondiente en el periodo 202005, por un monto de cobertura   de S/ 0 durante el periodo mayo del 2020.
Se detectaron 42 garantía(s) faltantes en   el registro correspondiente en el periodo 202006, por un monto de cobertura   de S/ 0 durante el periodo junio del 2020.
Se detectaron 59 garantía(s) faltantes en   el registro correspondiente en el periodo 202007, por un monto de cobertura   de S/ 0 durante el periodo julio del 2020.
Se detectaron 45 garantía(s) faltantes en   el registro correspondiente en el periodo 202008, por un monto de cobertura   de S/ 0 durante el periodo agosto del 2020.
Se detectaron 32 garantía(s) faltantes en   el registro correspondiente en el periodo 202009, por un monto de cobertura   de S/ 0 durante el periodo setiembre del 2020.
Se detectaron 14 garantía(s) faltantes en   el registro correspondiente en el periodo 202010, por un monto de cobertura   de S/ 0 durante el periodo octubre del 2020.

En todas dice 0.00, o es un problema de la Coopac? 

11. No sería necesaria la presencia de la cadena "Valores correctos: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 99" en los predicados de los errores 6XX. 
@

**Comment by diego-pacheco-PE** [comment]
12. Se detectaron 9125 crédito(s) con errores en el Número y Tipo de Documento (NID, TID) respectivamente, correspondiente a la base de datos crediticia BD01 durante el periodo setiembre del 2019.

Testee por separado un archivo que modifique selectivamente y me salió este error, medio raro.

**Comment by diego-pacheco-PE** [comment]
13. No veo la validación de fecha errónea o vacía del fppk, agregar esa y cualquier otro campo de fecha.

**Comment by diego-pacheco-PE** [comment]
14. Ya que sabemos que los layers son los que son, podemos modificar esta parte del log. 

[1] "[2021-01-30 20:44:25] - La validación operaciones duplicadas concluyó con 5 observación(es). (~ly2) "
[1] "[2021-01-30 20:44:30] - La validación de cruce interno concluyó con 3 observación(es). (~ly3) "
[1] "[2021-01-30 20:44:37] - La validación de los campos concluyó con 4 observaciones tipo1. (~ly4) "
[1] "[2021-01-30 20:44:40] - La validación de los campos concluyó con 3 observación(es) tipo2. (~ly4) "
[1] "[2021-01-30 20:44:40] - La revisión errores OM 22269-2020 tiene observaciones."

**Comment by diego-pacheco-PE** [comment]
15. En esta observación: "Se detectaron 6 crédito(s) con cronogramas duplicado(s) en el mes de Enero con un saldo de colocaciones por S/ 16641.56 durante el periodo enero del 2019." 
Tomamos esos 06 códigos de crédito, eliminamos duplicados, y consultamos sus valores en la BD01, sumamos lo obtenido y es lo que mostramos. Estoy probando los andes, please corroborar.

**Comment by diego-pacheco-PE** [comment]
16. Hay un error 609 que dice: "Se detectaron 26190 crédito(s) con dígitos diferentes o vacíos en la Forma de cancelación de la cuota (FOCAN) de la BD02A durante el periodo enero del 2019. Valores correctos: 1, 2, 3, 4, 5" Pero en los hechos, toda la cartera tiene 26190, no deberíamos decir en estos casos que toda la columna está vacía? Lo raro es que no hay un error 203 que diga esto. 

La lógica es, si hay un 203 que dice que FOCAN está vacía, la validación de la 609 no debe darse.

**Comment by diego-pacheco-PE** [comment]
_Si el aplicativo tiene éxito (que esta asegurado con el apoyo de ALC), debe tener 3 módulos. 
1. Módulo de validación de información crediticia
2. Módulo de alertas regulatorias 
3. Módulo de análisis de base de datos crediticias_

**Comment by diego-pacheco-PE** [comment]
17. Agreguemos este error: en todas las BD04 que nos manden, no pueden haber CCR_C que se repitan, sería tan ilógico como creer que un crédito lo puedes cancelar dos veces. La mejor forma de validarlo sería agarrar el CCR_C de todos los BD04 y aplicarle un n_distinct, si hay alguno que cae, sacamos el error. Es un error que tenemos que hacerlo, no por periodo si no en general. Ojo tenemos que proceder, si y solo si, no existan columnas faltantes CCR_C, si no salta error. 

Para el análisis tenemos que generar una base de créditos cancelados, por eso se me ocurrió el error.

**Comment by diego-pacheco-PE** [comment]
18. Mejor el 17 lo hacemos en el modulo de análisis, para ya dejar cerrado el modulo de validación. 
19. Borrar carpeta que dice sabana aelu 
20. Incorporar las 3 spreadsheets en un solo file. Prioridad 2.

**Comment by diego-pacheco-PE** [comment]
21. Estoy pensando tirar la conciliación contable al modulo de análisis. El cuadre contable no es requisito para ninguna otra validación o si?

**Comment by diego-pacheco-PE** [comment]
22. redundamos ambos numeros, borrar uno de los dos.
![image](https://user-images.githubusercontent.com/74920572/106376213-10d05b80-6361-11eb-9920-8b11f35588b5.png)

**Comment by diego-pacheco-PE** [comment]
23. Consulta, nuestro programa aguantaría el cambio de este parámetro?
https://github.com/SACOOP-PE/SIA-Analitica-PE/blob/b237ca1815767a2a02e9a590e386539376d20f08/R/main.R#L33
O sea que mañana te dijeron valida solo la bd1 y la bd2a que nos dieron hoy, el programa se caería? agenda hacer esas pruebas, prioridad 3.

**Comment by diego-pacheco-PE** [comment]
24. Recuérdame siempre que nos olvidamos de poner en la BD01 (esto si es relevante) los provisiones requeridas, y la tabla de provisión que aplicada crédito. En la BD01 pedimos la PCI (provisiones constituidas) pero la que se calcula en automático son las requeridas ...

**Comment by diego-pacheco-PE** [comment]
25. la solución al 24 sería cruzar los códigos de créditos con el anexo 6, pero es muy pesada la data, un config así pesaría 1GB, la solución sería conectar el R con el DWH.

26. hay forma de no ver el código en azul ?
![image](https://user-images.githubusercontent.com/74920572/106411399-3c138300-6413-11eb-9c5f-afb01d41382a.png)

**Comment by diego-pacheco-PE** [comment]
27. Please reordena el script reporting-manager.R
![image](https://user-images.githubusercontent.com/74920572/106411648-bd6b1580-6413-11eb-9db2-52511792d460.png)
No big deal, solo modifica los nombres y agrupa las funciones, ojo que el modulo 1 y 2 (validación y alertas reg.) tendrán el mismo proceso de reporting.

**Comment by diego-pacheco-PE** [comment]
28. así quedo ordenado el script utils.R
![image](https://user-images.githubusercontent.com/74920572/106411766-00c58400-6414-11eb-80a7-337a90a2db23.png)

**Comment by diego-pacheco-PE** [comment]
29. usar con discreción el library(xlsx) es java-based y luego hay errores jodidos, hasta que no tengamos la workstation no nos la podemos rifar. Vamos a usarlo para exportar y al primer error por java lo cambiamos.

**Comment by diego-pacheco-PE** [comment]
30. told ya
![image](https://user-images.githubusercontent.com/74920572/106412134-efc94280-6414-11eb-9dae-e371956beddb.png)

**Comment by diego-pacheco-PE** [comment]
31. Edwin usar este código para exportar a excel. 
```
library(openxlsx) # loads library and doesn't require Java installed

your_df_list <- c("df1", "df2", ..., "dfn")

for(name in your_df_list){
  write.xlsx(x = get(name), 
             file = "your_spreadsheet_name.xlsx", 
             sheetName = name)
}
```

La función que está ahorita no permite varias hojas, y la xlsx requiere java. 
Los archivos que debe generar son 
1. 434.log
2. Resultados-434.xlsx
3. Detalle-434.xlsx

El nuevo archivo es detalle-434.xlsx, debemos tener una hoja de excel por cada error, en donde si un error observa 40 créditos, en esa hoja excel te reporte los 40 créditos. Como no hay un identificado por cada error, se me ocurre que podemos usar el código del error y el nombre del archivo como identificador, por ejemplo: 304_01172_BD01_202009

**Comment by edwin-roque-0723** [comment]
1. Ok Diego ya revisé todo lo que encontraste para mejorar o añadir, lo estaré implementando esta semana y bueno ya estos días definiremos las alertas con Óscar para pasarlas a implementar en R. 
2.  Quedo atento a cualquier cambio adicional que quisieras hacer no hay problema.
3.  Voy a probar con Los Andes para corroborar los resultados, me parece raro sobre las fechas me imagino que la función getColVacia detecta los "" y no los "NA", si añado en el evaluarFile que lea los "NA" como "" detectará también en los campos fecha u otros similares que tengan "NA" en la función getColVacia , lo estaré probando.
4. Sobre el 29, 30, 31 si usé esa librería pero me saltaba error de java y lo dejé, buscaré si hay otra forma.
5. Sobre el cuadre contable no hay problema, no enlaza con ningún layer. Solo que siempre se filtran los archivos que tengan las columnas que se usarán para esa validación para que no salté un error en algunas columnas de los capitales, intereses, etc al no tener datos o que sean faltantes.
