### ISSUE TITLE
Evaluate the use of colr library 

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#4]
Revisar el uso de colr library, tratemos de usar tidyverse.

ref. src/1. Librerias_opciones.R

**Comment by edwin-roque-0723** [comment]
El uso que le doy a ese librería se origina al problema que no se le puede poner asignar un  texto como el nombre de un campo en un filter. Al momento de evaluar las columnas en el layer 4 no reconocía como tal esas columnas cuando las introducía como un texto o un caracter,  con esta librería ayuda a encontrar el campo de la BD con un texto.
