### ISSUE TITLE
CIS not found error / dailycheck 12022020

### ISSUE THREAD

**Issue by diego-pacheco-PE** [SACOOP-PE/SIA-Analitica-PE#9]
Periodos: 202001, 202002.

```
[1] "El layer 2 terminó: Wed Dec 02 9:50:48 PM 2020"
[1] "El layer 3 terminó: Wed Dec 02 9:50:56 PM 2020"
 Error: object 'CIS' not found
Run `rlang::last_error()` to see where the error occurred. 
36.
stop(fallback) 
35.
signal_abort(cnd) 
34.
abort(conditionMessage(cnd), parent = cnd) 
33.
h(simpleError(msg, call)) 
32.
.handleSimpleError(function (cnd) 
{
    abort(conditionMessage(cnd), parent = cnd)
}, "object 'CIS' not found", base::quote(eval_tidy(enquo(var),  ... 
31.
eval_tidy(enquo(var), set_names(seq_along(vars), vars)) 
30.
withCallingHandlers(expr, simpleError = function(cnd) {
    abort(conditionMessage(cnd), parent = cnd)
}) 
29.
instrument_base_errors(loc <- eval_tidy(enquo(var), set_names(seq_along(vars), 
    vars))) 
28.
tidyselect::vars_pull(names(.data), !!enquo(var)) 
27.
pull.data.frame(., CIS) 
26.
pull(., CIS) 
25.
function_list[[k]](value) 
24.
withVisible(function_list[[k]](value)) 
23.
freduce(value, `_function_list`) 
22.
`_fseq`(`_lhs`) 
21.
eval(quote(`_fseq`(`_lhs`)), env, env) 
20.
eval(quote(`_fseq`(`_lhs`)), env, env) 
19.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
18.
getInfoTotal(carpeta, periodo, BD03A) %>% pull(CIS) 
17.
setdiff(getInfoTotal(carpeta, periodo, BD03A) %>% pull(CIS), 
    getInfoTotal(carpeta, periodo, BD01) %>% pull(CIS)) 
16.
eval(lhs, parent, parent) 
15.
eval(lhs, parent, parent) 
14.
setdiff(getInfoTotal(carpeta, periodo, BD03A) %>% pull(CIS), 
    getInfoTotal(carpeta, periodo, BD01) %>% pull(CIS)) %>% unique() 
13.
procesarErrorcodDeudor(carpeta, Periodo, "BD03A", "BD01") 
12.
mutate_impl(.data, dots, caller_env()) 
11.
mutate.tbl_df(., vf_CodDeudor = procesarErrorcodDeudor(carpeta, 
    Periodo, "BD03A", "BD01")) 
10.
mutate(., vf_CodDeudor = procesarErrorcodDeudor(carpeta, Periodo, 
    "BD03A", "BD01")) 
9.
function_list[[i]](value) 
8.
freduce(value, `_function_list`) 
7.
`_fseq`(`_lhs`) 
6.
eval(quote(`_fseq`(`_lhs`)), env, env) 
5.
eval(quote(`_fseq`(`_lhs`)), env, env) 
4.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
3.
tibble(Periodo = restriccionPeriodos(errorBucket, "BD01", "BD03A", 
    "CIS")) %>% rowwise() %>% mutate(vf_CodDeudor = procesarErrorcodDeudor(carpeta, 
    Periodo, "BD03A", "BD01")) %>% rowwise() %>% pull(vf_CodDeudor) %>% 
    paste(collapse = ",") %>% strsplit(",") 
2.
ejecutarValidacionLayer4(header, eb) 
1.
main(header, eb) 


```

Los tiempos están geniales.
~Diego P.

**Comment by edwin-roque-0723** [comment]
Voy a revisar eso, creo que en esos periodos el campo CIS no está o está vacío totalmente. Pero me parece raro que diga que no encuentra ese campo en la 1 y la 3A.

**Comment by edwin-roque-0723** [comment]
Sorry la hora, acabo de probar al código justo para esos dos periodos donde sale ese error y si corre bien. 

> header        <- initHeader(idCoopac = "01172",
+                              coopacCarpeta  = "C:/Users/eroque/Desktop/Proyecto_BDCC",
+                              periodoInicial = "202001",
+                              periodoFinal   = "202002",
+                              bds            = list(c("BD01", "BD02A", "BD02B", "BD03A", "BD03B", "BD04")))
> eb            <- initBucketErrores(header)
> listaErrores <- main(header, eb)
[1] "El layer 1 terminó: mié. Dic. 02 10:40:09 2020"
|====================================| 100%   55 MB
|====================================| 100%   55 MB
[1] "El layer 2 terminó: mié. Dic. 02 10:40:23 2020"
|====================================| 100%   56 MB
|====================================| 100%    6 MB
|====================================| 100%   56 MB
[1] "El layer 3 terminó: mié. Dic. 02 10:40:41 2020"
|====================================| 100%   55 MB
|====================================| 100%   56 MB
`summarise()` regrouping output by 'Coopac', 'NombCoopac', 'Carpeta', 'IdProceso', 'Cod' (override with `.groups` argument)
|====================================| 100%    6 MB
`summarise()` regrouping output by 'Coopac', 'NombCoopac', 'Carpeta', 'IdProceso', 'Cod' (override with `.groups` argument)
[1] "El layer 4 terminó: mié. Dic. 02 10:41:20 2020"
>

**Comment by edwin-roque-0723** [comment]
El problema no es el código R sino en la codificación de algunos archivos y hay conflictos con los datos porque no separan los campos y por eso no encuentra el campo CIS en la 3A. Se tiene que aplicar una conversión, ya se tiene un procedimiento en powerShell, lo subiré.
